### ISSUE TITLE
Create a demo

### ISSUE THREAD

**Issue by msurguy** [NikitaGolovko/jQuery-DataList#6]
Is there a quick demo of the plugin that you could mention in the readme file?

Please let me know when you have one and I'll feature this plugin on Bootsnipp resources. Thanks!

**Comment by NikitaGolovko** [comment]
Hey Maksim.
Sorry for the late response. The readme file was updated with the link to
the sample page. Additionally I created the GitHub page for it as well, if
it works better (http://nikitagolovko.github.io/jQuery-DataList/) which
also features a functional sample. Let me know if this works or if you'd
like me to re-submit the extension again through the site.
Thanks
Nikita

**Comment by msurguy** [comment]
Ok, thanks for doing that, I've added the plugin to Bootsnipp resources
page: http://bootsnipp.com/resources

Enjoy!

On Tue, Jun 3, 2014 at 7:19 PM, Nikita notifications@github.com wrote:

> Hey Maksim.
> Sorry for the late response. The readme file was updated with the link to
> the sample page. Additionally I created the GitHub page for it as well, if
> it works better (http://nikitagolovko.github.io/jQuery-DataList/) which
> also features a functional sample. Let me know if this works or if you'd
> like me to re-submit the extension again through the site.
> Thanks
> Nikita
> 
> On Mon, May 26, 2014 at 11:45 PM, Maksim Surguy notifications@github.com
> 
> wrote:
> 
> > Is there a quick demo of the plugin that you could mention in the readme
> > file?
> > 
> > Please let me know when you have one and I'll feature this plugin on
> > Bootsnipp resources. Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/NikitaGolovko/jQuery-DataList/issues/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NikitaGolovko/jQuery-DataList/issues/6#issuecomment-45045088
> .

## 

---
- Maks

**Comment by NikitaGolovko** [comment]
This has been resolved and can be closed.
Thank you to Maksim for featuring the extension.
